urls.py
from django.conf.urls import include, url
from views import *

beschrijving_patterns = [
    url(r'^uitgangspunten/$', bestuursmodel, name='bestuursmodel_uitgangspunten'),
    url(r'^sectoren/$', bestuursmodel, name='bestuursmodel_sectoren'),
    url(r'^uitwerking/$', bestuursmodel, name = 'bestuursmodel_uitwerking'),
    url(r'^planningcontrol/$', bestuursmodel, name = 'bestuursmodel_planningcontrol'),
]

urlpatterns = [
    url(r'^$', bestuursmodel, name='bestuursmodel_inleiding'),
    url(r'^afdelingen/$', afdelingen, name='afdelingen'),
    url(r'^afdeling/$', afdeling),
    url(r'^afdeling/(\w+)/$', afdeling, name='afdeling'),
    url(r'^afdeling/(\w+)/(\w+)/$', afdeling),
    url(r'^functies/$', functies, name='functies'),
    url(r'^functie/(\w+)/$', functie, name='functie'),
    url(r'^inleiding/', include(beschrijving_patterns)),
]

models.py
from django.db import models
from django.core.urlresolvers import reverse
from mptt.models import MPTTModel, TreeForeignKey

class Afdeling(MPTTModel):
    nummer = models.PositiveIntegerField(unique=True)
    naam = models.CharField(max_length=45, unique=True)
    taakbeschrijving = models.TextField("Taakbeschrijving")
    rapporteert_aan = TreeForeignKey("Afdeling",
                                      related_name="afdelingen",
                                      blank=True, null=True)
    sector = models.ForeignKey("Sector",
                                 related_name="afdelingen",
                               blank=True, null=True)
    permanent = models.BooleanField(default=True)
    startdatum = models.DateField(blank=True, null=True)
    einddatum = models.DateField(blank=True, null=True)
    functies = models.ManyToManyField("Functie", through='Afdeling_Functie',
                                                related_name="afdelingen")

    class Meta:
        ordering = ["naam"]
        verbose_name_plural = "Afdelingen"

    class MPTTMeta:
        parent_attr = "rapporteert_aan"
        order_insertion_by = ["nummer"]

    def __unicode__(self):
        return self.naam

class Functie(models.Model):
    naam = models.CharField(max_length=100, unique=True)
    beschrijving = models.TextField("Functiebeschrijving")
    functietype = models.ForeignKey('FunctieType',
                                 blank=True, null=True)
    taken = models.ManyToManyField("FunctieTaak", through='FunctieTaakDetails')
                                 
    class Meta:
        ordering = ["naam"]
        verbose_name_plural = "Functies"
        
    def get_absolute_url(self):
        return reverse('functie-detail', kwargs={'pk': self.pk})

    def __unicode__(self):
        return self.naam
        
class Afdeling_Functie(models.Model):
    """ To store the m2m relation between Afdeling and Functie
    """
    afdeling = models.ForeignKey(Afdeling)
    functie = models.ForeignKey(Functie)
    beschrijving = models.CharField(max_length=100)

class Taak(models.Model):
    """ Taak die behoort bij een afdeling
        Taken die behoren bij een functie worden opgeslagen in het model FunctieTaak
    """
    naam = models.CharField(max_length=100, unique=True)
    beschrijving = models.TextField("Taakbeschrijving",
                                    blank=True, null=True)
    nummer = models.IntegerField(default=10)
    afdeling = models.ForeignKey("Afdeling",
                                 related_name="taken",
                                 blank=True, null=True)

    class Meta:
        ordering = ["nummer"]
        verbose_name_plural = "Afdelingstaken"

    def __unicode__(self):
        return self.naam

class FunctieType(models.Model):
    naam = models.CharField(max_length=100, unique=True)

    class Meta:
        ordering = ["naam"]
    
    def __unicode__(self):
        return self.naam

        
class FunctieTaak(models.Model):
    """ Taak die behoort bij een Functie
        Taken die behoren bij een Afdeling worden opgeslagen in model Taak
    """
    naam = models.CharField(max_length=100, unique=True)
    beschrijving = models.TextField("Taakbeschrijving",
                                    blank=True, null=True)
    functietype = models.ForeignKey('FunctieType',
                                 blank=True, null=True)

    class Meta:
        ordering = ["naam"]
        verbose_name = "Taak"
        verbose_name_plural = "Functietaken"
    
    def __unicode__(self):
        return self.naam


class FunctieTaakDetails(models.Model):
    functietaak = models.ForeignKey("FunctieTaak", verbose_name="taak")
    functie = models.ForeignKey("Functie", related_name="functietaakdetails") 
    uur_per_maand = models.IntegerField()

class Verantwoordelijkheid(models.Model):
    """
    Verantwoordelijkheden worden kunnen worden toegekend aan een rol of een afdeling
    """
    naam = models.CharField(max_length=100, unique=True)
    beschrijving = models.TextField("beschrijving")
    afdeling = models.ForeignKey(Afdeling,
                                 related_name='verantwoordelijkheden',
                                 blank=True, null=True)

    class Meta:
        ordering = ["naam"]
        verbose_name_plural = "Verantwoordelijkheden"

    def __unicode__(self):
        return self.naam


class Bevoegdheid(models.Model):
    """
    Bevoegdheden worden kunnen worden toegekend aan een afdeling
    """
    naam = models.CharField(max_length=100, unique=True)
    beschrijving = models.TextField("beschrijving")
    afdeling = models.ForeignKey(Afdeling,
                                 related_name='bevoegdheden',
                                 blank=True, null=True)

    class Meta:
        ordering = ["naam"]
        verbose_name_plural = "Bevoegdheden"

    def __unicode__(self):
        return self.naam

class FunctieEis(models.Model):
    naam = models.CharField(max_length=100, unique=True)
    beschrijving = models.TextField("beschrijving")
    functies = models.ManyToManyField("Functie",
                                      related_name="functie_eisen",
                                      verbose_name="Functie eisen")
    class Meta:
        ordering = ["naam"]
        verbose_name_plural = "Functie-eisen"

    def __unicode__(self):
        return self.naam


class Sector(models.Model):
    naam = models.CharField(max_length=100, unique=True)
    kleur = models.CharField(max_length=15)
    beschrijving = models.TextField("beschrijving")
    class Meta:
        ordering = ["naam"]
        verbose_name_plural = "Sectoren"

    def __unicode__(self):
        return self.naam


templates/afdeling.html
{% extends "bestuursmodel_base.html" %}
{% block main_panel %}
    <h1>{% block title %}Bestuursmodel SVW'27{% endblock %}</h1>
    <h2>{{ afdeling.naam }}</h2>
    {{ afdeling.taakbeschrijving|linebreaksbr }}
    {% if afdeling.rapporteert_aan %}
        {{ afdeling.naam }} rapporteert aan <a href="/bestuursmodel/afdeling/{{afdeling.rapporteert_aan.id}}"> {{afdeling.rapporteert_aan.naam}}</a>.
    {% endif %}

    <h3>Taken</h3>
    {% include "afdeling_taken.html" %}

    {% if afdeling.get_children %}
        <h3>Afdelingen en commissies</h3>
        {% include "afdeling_children.html" %}
    {% endif %}

    {% if afdeling.functies.count %}
        <h3>Functies</h3>
        {% include "afdeling_functies.html" %}
    {% endif %}
{% endblock %}

templates/afdeling_functies.html
	{% if afdeling.functies.count %}
		<ul>{% for functie in afdeling.functies.all %}
			<li><a href="/bestuursmodel/functie/{{functie.id}}"> {{functie.naam}} </a></li>
		{% endfor %}
		</ul>
	{% else %}
		{{ afdeling.naam }} heeft geen functies
	{% endif %}

templates/afdeling_taken.html
	{% if afdeling.taken.count %}
		<ul>{% for taak in afdeling.taken.all %}
			<li>{{taak.naam}}</li>
			{{taak.beschrijving|linebreaksbr}}
		{% endfor %}
		</ul>
	{% else %}
		{{ afdeling.naam }} heeft geen taken
	{% endif %}

templates/afdeling_verantwoordelijkheden.html
	{% if afdeling.verantwoordelijkheden.count %}
		<ul>{% for verantwoordelijkheid in afdeling.verantwoordelijkheden.all %}
			<li><a href="/bestuursmodel/verantwoordelijkheid/{{verantwoordelijkheid.id}}"> {{verantwoordelijkheid.naam}} </a></li>
		{% endfor %}
		</ul>
	{% else %}
		{{ afdeling.naam }} heeft geen verantwoordelijkheden
	{% endif %}

templates/bestuursmodel.html
{% extends "bestuursmodel_base.html" %}
{% load mptt_tags %}

{% block main_panel %}
<h1>{% block title %}Bestuursmodel SVW'27{% endblock %}</h1>
<h2>{{ title }}</h2>
{% include detail_html %}
<nav>
  <ul class="pager">
    <li {% if sublink == 'inleiding' %}class="disabled"{% endif %}>
        <a href="{% url 'bestuursmodel_inleiding' %}">Inleiding</a>
    </li>
    <li {% if sublink == 'uitgangspunten' %}class="disabled"{% endif %}>
        <a href="{% url 'bestuursmodel_uitgangspunten' %}">Uitgangspunten</a>
    </li>
    <li {% if sublink == 'sectoren' %}class="disabled"{% endif %}>
        <a href="{% url 'bestuursmodel_sectoren' %}">Sectoren</a>
    </li>
    <li {% if sublink == 'uitwerking' %}class="disabled"{% endif %}>
        <a href="{% url 'bestuursmodel_uitwerking' %}">Uitwerking</a>
    </li>
    <li {% if sublink == 'planningcontrol' %}class="disabled"{% endif %}>
        <a href="{% url 'bestuursmodel_planningcontrol' %}">Planning & Control</a>
    </li>
  </ul>
</nav>
{% endblock %}

templates/bestuursmodel_base.html
{% extends "base.html" %}
{% load mptt_tags %}


{% block right_panel %}
    <br>
    <a href="{% url 'bestuursmodel_inleiding' %}">Inleiding</a><br>
    <a href="{% url 'bestuursmodel_uitgangspunten' %}">Uitgangspunten</a><br>
    <a href="{% url 'bestuursmodel_sectoren' %}">Sectoren</a><br>
    <a href="{% url 'bestuursmodel_uitwerking' %}">Uitwerking</a><br>
    <a href="{% url 'bestuursmodel_planningcontrol' %}">Planning en controlecyclus</a><br>
    
    {% for root_afd in root_afd %}
        <h4><a href="{% url 'afdeling' root_afd.id %}">{{root_afd.naam}}</a></h4>
        {% for afdeling in root_afd.afdelingen.all %}
            <a href="{% url 'afdeling' afdeling.id %}">{{afdeling.naam}}</a><br>
        {% endfor %}        
    {% endfor %}

    <h4><a href="{% url 'afdelingen' %}">Afdelingen en Commissies</a></h4>
     <h4><a href="{% url 'functies' %}">Functies</a></h4>
{% endblock %}

templates/bestuursmodel_navbar.html
<li class="dropdown">
    <a href="{% url 'bestuursmodel_inleiding' %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Bestuursmodel SVW'27<span class="caret"></span></a>
    <ul class="dropdown-menu">
        <li>
            <a href="{% url 'bestuursmodel_inleiding' %}">Inleiding</a>
        </li>
        <li>
            <a href="{% url 'bestuursmodel_uitgangspunten' %}">Uitgangspunten</a>
        </li>
        <li>
            <a href="{% url 'bestuursmodel_sectoren' %}">Sectoren</a>
        </li>
        <li>
            <a href="{% url 'bestuursmodel_uitwerking' %}">Uitwerking</a>
        </li>
        <li>
            <a href="{% url 'bestuursmodel_planningcontrol' %}">Planning & Control</a>
        </li>
        <li role="separator" class="divider"></li>
         <li>
            <a href="{% url 'afdelingen' %}">Afdelingen en Commissies</a>
        </li>
        <li>
            <a href="{% url 'functies' %}">Functies</a>
        </li>
   </ul>
</li>

templates/bestuursmodel_planningcontrol.html
<h4>Inleiding</h4>
<p>De planning- en controlecyclus (P&C cyclus) bestaat uit jaarlijks terugkerende en op elkaar aansluitende activiteiten die gericht zijn op het opstellen, plannen, uitvoeren en verantwoorden van het
(meerjaren) beleid van SVW’27. In de verschillende fases wordt de noodzakelijke bestuurlijke informatie vanuit alle sectoren/afdelingen in samenhang bij elkaar gebracht en voorgelegd aan
het hoofdbestuur en de Algemene Leden Vergadering.</p>
<p>Door toepassing van de P&C cyclus bereiken we transparantie en samenhang in de ontwikkelingen en uitvoering van het beleid van SVW’27. Zo wordt de begroting niet alleen een
financiële aangelegenheid maar worden aan de toegekende budgetten tevens de te verwachten resultaten gekoppeld. Gaande weg het lopende jaar zal worden gerapporteerd over de
voortgang en ontwikkelingen, waardoor tussentijdse bijstelling kan worden overwogen.</p>
<h4>De cyclus</h4>
<p>In alle fases van planning- en controlecyclus worden op eenduidige wijze de volgende aspecten belicht waardoor in totale samenhang de bestuurlijke informatie wordt gebundeld:
<ul>
    <li>Beleidsuitgangspunten</li>
    <li>Doelstellingen uit beleid</li>
    <li>Doelstellingen / jaarplannen van de afdelingen</li>
    <li>Financiën</li>
    <li>Personele bezetting</li>
    <li>Jaarplanningen</li>
    </ul>
</p>
<p>De cyclus loopt per kalenderjaar en kent de onderstaande fases / activiteiten en planning.
<table class="table table-bordered table-condensed table-hover">
    <tr><th>Fase</th><th>Activiteiten</th><th>Planning</th></tr>
    <tr><td>Jaarrekening</td><td>Verantwoording over de resultaten van het afgelopen jaar</td><td>Maart</td></tr>
    <tr><td>Voorjaarsnota</td><td>Aandragen beleidsintensiveringen tbv begroting</td><td>April</td></tr>
    <tr><td>Bestuursrapportage 1</td><td>Rapportage voortgang en ontwikkelingen lopende jaar (januari-april).</td><td>Mei</td></tr>
    <tr><td>Algemene Ledenvergadering voorjaar</td><td>Verantwoording over de resultaten van het afgelopen jaar</td><td>Mei</td></tr>
    <tr><td>Begroting</td><td>Financiële uitgangspunt voor komend jaar</td><td>Oktober</td></tr>
    <tr><td>Bestuursrapportage 2</td><td>Rapportage voortgang en ontwikkelingen lopende jaar (mei-september)</td><td>Oktober</td></tr>
    <tr><td>Jaarplannen</td><td>Jaarplannen (en planningen) voor komend jaar</td><td>Oktober</td></tr>
    <tr><td>Algemene Ledenvergadering najaar</td><td>Presentatie / vaststelling: bestuursrapportage 2, begroting en jaarplannen</td><td>November</td></tr>
</table>
</p>

templates/bestuursmodel_uitgangspunten.html
<p>De volgende uitgangspunten zijn leidend:
<ul>
<li>Beperkt tijdsbeslag</li>
In tegenstelling tot het verleden heeft men doorgaans niet veel tijd beschikbaar voor vrijwilligerswerk. Ook voor bestuurders geldt dat tijd kostbaar is.
<li>Differentiatie in functies</li>
Hierdoor kan meer specialisme ontstaan met meer focus waardoor de kwaliteit toeneemt en de beschikbare tijd optimaal wordt benut.
<li>Slagvaardig</li>
Specialisaties die voorheen dieper in de organisatie zaten worden op bestuursniveau gebracht. Door de korte directe contacten kan er slagvaardiger worden bestuurd en zijn de bestuursleden onderling beter geïnformeerd (korte lijnen).
<li>Beslissingen laag in de organisatie</li>
Veel beslissingen kunnen laag in de organisatie worden genomen. Dit bevordert de slagvaardigheid van de vereniging.
<li>Continuïteit</li>
Alle bestuursleden vertegenwoordigen een afdeling en zullen voor deze afdeling een meerjarenplan opstellen.
</ul>
</p>
<p>Het hoofdbestuur zal zich vooral richten op het vaststellen en actualiseren van het beleid en de samenhang tussen de meerjarenplannen van de afdelingen. Tevens zal het hoofdbestuur werkgroepen voor specifieke projecten aanstellen en coördineren.</p>

templates/bestuursmodel_uitwerking.html
<h4>Hoofdbestuur</h4>
<p>Alle bestuursleden van alle afdelingen vormen gezamenlijk het hoofdbestuur. Het hoofdbestuur vergadert minimaal één keer per maand.</p>
<h4>Beleid</h4>
<p>Het hoofdbestuur zal zich vooral richten op het vaststellen en actualiseren van het beleid van de vereniging.</p>
<h4>Meerjarenplannen</h4>
<p>Om dit te ondersteunen is de eerste taak van ieder bestuurslid het opstellen van een meerjarenplan van zijn afdeling. Dit plan dient aan te sluiten bij het verenigingsbeleid, bevat de te behalen doelen en is de basis voor de begroting van de afdeling. Binnen het hoofdbestuur worden de meerjarenplannen geaccordeerd en op elkaar afgestemd zodat ieder in hetzelfde tempo loopt.</p>
<h4>Verantwoordelijkheden</h4>
<p>Budget- en beslissingsverantwoordelijkheid komt zo laag mogelijk in de organisatie te liggen. Ieder bestuurslid krijgt hiermee een eigen verantwoording, maar legt deze ook af in hoofdbestuur.</p>
<h4>Vervanger</h4>
<p>Ieder bestuurslid zorgt voor een tweede man, waardoor er te allen tijde een vertegenwoordiger van de afdeling op de hoofdbestuursvergadering aanwezig kan zijn. Tevens is deze tweede man een extra aanspreekpunt binnen de afdeling en kan hij zorgen voor een verdeling van de tijdsbelasting.</p>
<h4>Werkgroepen</h4>
<p>Indien het hoofdbestuur dit noodzakelijk acht zal het hoofdbestuur werkgroepen voor specifieke projecten aanstellen en coördineren.</p>

templates/functie.html
{% extends "bestuursmodel_base.html" %}
{% block main_panel %}
    <h1>{% block title %}Bestuursmodel SVW'27{% endblock %}</h1>

	<h2>{{ functie.naam }}</h2>
    {{ functie.beschrijving|linebreaksbr }}

    <h3>Plaats in de organisatie</h3>
    {{ functie.naam }} maakt deel uit van de volgende afdelingen:
    {% for afdeling_functie in functie.afdeling_functie_set.all %}
        <ul>
            <li><a href="{% url 'afdeling' afdeling_functie.afdeling.id %}">{{ afdeling_functie.afdeling }}</a>
            {% if afdeling_functie.beschrijving %}
                : {{ afdeling_functie.beschrijving|linebreaksbr }}
            {% endif %}
            </li>
        </ul>
    {% endfor %}
    <h3>Taken</h3>
    {% include "functie_taken.html" %}

    <h3>Functie-eisen</h3>
    {% include "functie_eisen.html" %}

{% endblock %}

templates/functie_eisen.html
	{% if functie.functie_eisen.count %}
		<ul>
            {% for functie_eis in functie.functie_eisen.all %}
                <li>{{functie_eis.beschrijving|linebreaksbr}}</li>
            {% endfor %}
		</ul>
	{% else %}
		{{ functie.naam }} heeft geen functie-eisen.
	{% endif %}

templates/functie_taken.html
	{% if functie.functietaakdetails.count %}
        <table class="table table-condensed table-bordered">
            <thead>
                <tr>
                    <th>Taak</th>
                    <th>Uur per maand</th>
                </tr>
            </thead>
            <tbody>
                {% for ft in functie.functietaakdetails.all %}
                    <tr>
                        <td>{{ft.functietaak}}</td>
                        <td>{{ft.uur_per_maand}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        {% if functie.functietaakdetails.count > 1 %}
             <tfoot>
                <tr>
                    <th>Totaal</th>
                    <th>{{uurtotaal.uur_per_maand__sum}}</th>
                </tr>
            </tfoot>
       {% endif %}
       </table>
	{% else %}
		{{ functie.naam }} heeft geen taken.
	{% endif %}

templates/functies.html
{% extends "bestuursmodel_base.html" %}
{% block main_panel %}
    <h3>Functies</h3>
    Het bestuursmodel definieert een groot aantal functies. Gebruik onderstaande zoekbalk om functies te zoeken<br><br>
    <form role="form search">
        <div class="input-group">
            <span class="input-group-btn">
                <button type="submit" class="btn btn-default">
                    <span class="glyphicon glyphicon-search"></span>
                </button>
            </span>
            <div class="form-group">
                <input type="text" name="q" value="{{query}}" class="form-control" placeholder="Zoek functie">
            </div>
        </div>
    </form>
    {% if query %}
        <h4>Gevonden functies</h4>
        {% if functies %}
            <ul>{% for functie in functies %}
                <li><a href="/bestuursmodel/functie/{{functie.id}}"> {{functie.naam}} </a></li>
                {% endfor %}
            </ul>
        {% else %}
                Geen functies gevonden
        {% endif %}
    {% endif %}

{% endblock %}